import { escapeLabelValueInSelector } from '../../../../languageUtils';

/** One include/exclude filter on a collapsed message pattern */
export interface PatternFilter {
  pattern: string;
  type: 'include' | 'exclude';
}

/**
 * Matches the whole _msg against a collapse_nums-style pattern. A plain filter —
 * no copy/collapse/restore round trip needed. Requires VictoriaLogs >= v1.33
 */
const matchExpr = (f: PatternFilter) => `pattern_match_full("${escapeLabelValueInSelector(f.pattern)}")`;

/**
 * Builds the LogsQL filter expression for the given pattern filters: includes are
 * OR-combined, excludes negated and AND-combined (implicit AND by juxtaposition)
 */
function buildPatternFilterExpr(filters: PatternFilter[]): string {
  const includes = filters.filter((f) => f.type === 'include');
  const excludes = filters.filter((f) => f.type === 'exclude');
  const parts: string[] = [];
  if (includes.length) {
    parts.push(includes.length > 1 ? `(${includes.map(matchExpr).join(' OR ')})` : matchExpr(includes[0]));
  }
  parts.push(...excludes.map((f) => `!(${matchExpr(f)})`));
  return parts.join(' ');
}

/**
 * Appends the pattern filters as a single `filter` pipe, so they compose with any
 * expression shape (the drawer's `*`-based queries as well as an editor expression
 * that already contains pipes). Original messages stay untouched — pattern_match_full
 * matches the collapsed shape in place
 */
export function applyPatternFilters(expr: string, filters: PatternFilter[]): string {
  if (!filters.length) {
    return expr;
  }
  const base = (expr ?? '').trim() || '*';
  return `${base} | filter ${buildPatternFilterExpr(filters)}`;
}

/** Start of a filter pipe generated by applyPatternFilters — also matches a hand-written equivalent */
const FILTER_PIPE_START = /\|\s*filter\s+!?\(*pattern_match_full\(/;

/** Temp field of the pre-v1.33 collapse/restore chain — recognized so an expression written by an older Apply still cleans up */
const LEGACY_CHAIN_START = ' | copy _msg as __vl_pf_msg';
const LEGACY_CHAIN_END = ' | rename __vl_pf_msg as _msg';

/**
 * Removes a previously appended pattern-filter pipe from the expression.
 * Makes "Go to editor" idempotent: the current filters replace the ones
 * written by an earlier Apply instead of stacking after them
 */
export function stripPatternFilterPipes(expr: string): string {
  let result = stripLegacyChain(expr);
  // bounded loop: each pass removes one occurrence, so it can't run more times than there are pipes
  for (let guard = 0; guard < 10; guard++) {
    const match = FILTER_PIPE_START.exec(result);
    if (!match) {
      break;
    }
    // the pattern text may contain `|` — walk to the end of this pipe respecting quoted literals
    let i = match.index + match[0].length;
    let inQuotes = false;
    for (; i < result.length; i++) {
      const ch = result[i];
      if (inQuotes && ch === '\\') {
        i++;
        continue;
      }
      if (ch === '"') {
        inQuotes = !inQuotes;
        continue;
      }
      if (ch === '|' && !inQuotes) {
        break;
      }
    }
    const head = result.slice(0, match.index).trim();
    const tail = result.slice(i).trim();
    result = tail ? `${head} ${tail}` : head;
  }
  return result;
}

function stripLegacyChain(expr: string): string {
  const start = expr.indexOf(LEGACY_CHAIN_START);
  if (start === -1) {
    return expr;
  }
  const end = expr.indexOf(LEGACY_CHAIN_END, start);
  if (end === -1) {
    return expr;
  }
  return (expr.slice(0, start) + expr.slice(end + LEGACY_CHAIN_END.length)).trim();
}

/** Returns the filters with the given pattern toggled: same type removes it, different type switches it */
export function togglePatternFilter(
  filters: PatternFilter[],
  pattern: string,
  type: PatternFilter['type']
): PatternFilter[] {
  const existing = filters.find((f) => f.pattern === pattern);
  const rest = filters.filter((f) => f.pattern !== pattern);
  if (existing?.type === type) {
    return rest;
  }
  return [...rest, { pattern, type }];
}
