victorialogs-backend-plugin-prod:
	APP_NAME=victoriametrics_backend_plugin $(MAKE) app-via-docker

victorialogs-backend-plugin-linux-amd64-prod:
	APP_NAME=victorialogs_backend_plugin $(MAKE) app-via-docker-linux-amd64

victorialogs-backend-plugin-linux-arm-prod:
	APP_NAME=victorialogs_backend_plugin $(MAKE) app-via-docker-linux-arm

victorialogs-backend-plugin-linux-arm64-prod:
	APP_NAME=victorialogs_backend_plugin $(MAKE) app-via-docker-linux-arm64

victorialogs-backend-plugin-linux-386-prod:
	APP_NAME=victorialogs_backend_plugin $(MAKE) app-via-docker-linux-386

victorialogs-backend-plugin-amd64-prod:
	APP_NAME=victorialogs_backend_plugin $(MAKE) app-via-docker-darwin-amd64

victorialogs-backend-plugin-arm64-prod:
	APP_NAME=victorialogs_backend_plugin $(MAKE) app-via-docker-darwin-arm64

victorialogs-backend-plugin-windows-prod:
	APP_NAME=victorialogs_backend_plugin $(MAKE) app-via-docker-windows-amd64
